version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.cacheNode
    ports:
      - "5001-5003:5000"
    environment:
        - ZOOKEEPER_HOST=zookeeper:2181
    scale: 3
    depends_on:
        - zookeeper

