# First stage: Build the Python environment and install dependencies
FROM python:3.9-slim AS builder

WORKDIR /app

# Copy requirements file
COPY ./cache-http/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Run app.py when the container launches
CMD ["python", "-m", "cache-http.cacheHTTPNode"]
