version: "3"

services:
  zookeeper:
   image: zookeeper:latest
   ports:
    - "2181:2181"

  web-server:
    build:
      context: "./Cache"
      dockerfile: Dockerfile
    ports:
      - 5000

    depends_on:
      - "zookeeper"

    deploy:
      replicas: 3
