version: "3"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.cacheNode
    expose:
      - "5000"
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
    scale: 3
    depends_on:
      - zookeeper

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.cacheGateway
    ports:
      - "5005:5005"
    environment:
      - GATEWAY_PORT=5005
      - ZOOKEEPER_HOST=zookeeper:2181
      - HOSTNAME=localhost
    # scale: 2
    depends_on:
      # - zookeeper
      - web
